/* =====================================================================
 * 肖阳晨的个人网站 — 内容数据文件
 * ---------------------------------------------------------------------
 * 这是你(站长)唯一需要编辑的文件。修改下面的文字、链接、坐标即可，
 * 无需改动其它任何代码。所有字段都支持直接编辑。
 *
 * 坐标格式：[经度, 纬度]，例如北京是 [116.407, 39.904]
 * 不知道坐标？搜索 “城市名 经纬度” 即可，或用文末常见城市坐标速查。
 * ===================================================================== */

window.SITE_DATA = {
  /* ---------- 1. 个人简介 ---------- */
  profile: {
    name: "肖阳晨",
    englishName: "阳晨·肖",
    tagline: "努力挣扎的规划研究生", // 原稿“龟话”按同音更正为“规划”，如需改回请告知
    avatar: "assets/avatar.webp",
    location: "中国 · 江西 · 南昌",
    // 个人简介：支持 Markdown 语法（**加粗**、*斜体*、- 列表、`代码`、> 引用 等）
    bio: [
      "出生于 **江西省南昌市南昌县**，本科毕业于 **南昌大学建筑与设计学院**，目前就读于 **青岛理工大学建筑与城乡规划学院**。",
      "",
      "说白了，就是一名 *书呆子钓鱼佬* 兼 *健身爱好者*。",
    ].join("\n"),
    contacts: [
      {
        type: "email",
        label: "邮箱",
        value: "738904585@qq.com",
        href: "mailto:738904585@qq.com",
      },
      {
        type: "github",
        label: "GitHub",
        value: "xxxyc-elite",
        href: "https://github.com/xxxyc-elite",
      },
    ],
  },

  /* ---------- 2. 兴趣爱好 ---------- */
  // icon 可用 emoji；tags 用于标签分类联动（点击标签会筛选相关卡片与地图标记）
  hobbies: [
    {
      icon: "🎣",
      name: "垂钓",
      desc: "台钓、路亚都来。",
      tags: ["户外", "垂钓", "放松"],
    },
    {
      icon: "✈️",
      name: "旅行",
      desc: "一年至少两趟长途。",
      tags: ["户外", "旅行", "摄影"],
    },
    {
      icon: "💪",
      name: "健身",
      desc: "目前卧推达到 120KG，硬拉和深蹲还在试探边界。",
      tags: ["运动"],
    },
  ],

  /* ---------- 3. 标签分类 ----------
   * 这里列出全站标签。点击任意标签会：
   *   - 过滤“兴趣爱好”卡片
   *   - 在地图上高亮带该标签的 旅行/垂钓 标记
   * 颜色用于地图标记与标签底色（可自由改）。
   */
  tags: [
    { name: "户外", color: "#2f9e6f" },
    { name: "旅行", color: "#3b82f6" },
    { name: "垂钓", color: "#0ea5e9" },
    { name: "摄影", color: "#a855f7" },
    { name: "生活", color: "#14b8a6" },
    { name: "放松", color: "#ec4899" },
    { name: "运动", color: "#f97316" },
    { name: "淡水", color: "#0891b2" },
  ],

  /* ---------- 4. 旅行去过的地方 ----------
   * type 固定为 "travel"。coord = [经度, 纬度]。
   * note 支持 Markdown。tags 与上方标签一致即可被筛选。
   * province / city / county = 行政归属（省 / 市 / 县或区），用于「省市县分类」与省级筛选。
   * img = 该地点配图地址（本地路径如 "assets/nanchang.jpg" 或网络图链）；留空则显示「配图待添加」占位。
   * 行政归属说明：直辖市/特别行政区只填 province（city/county 留空）；县级市/县填到 county。
   */
  travel: [
    {
      name: "南昌",
      coord: [115.858, 28.682],
      date: "2003.05",
      tags: ["旅行"],
      province: "江西省",
      city: "南昌市",
      county: "南昌县",
      img: "assets/nanchang.png",
      note: "出生地。",
    },
    {
      name: "深圳",
      coord: [114.057, 22.543],
      date: "2009.01 / 2012.01",
      tags: ["旅行"],
      province: "广东省",
      city: "深圳市",
      county: "",
      img: "assets/shenzhen.png",
      note: "随父母到姑姑家过年，游玩大梅沙与世界之窗。",
    },
    {
      name: "香港",
      coord: [114.173, 22.32],
      date: "2012.01",
      tags: ["旅行"],
      province: "香港特别行政区",
      city: "",
      county: "",
      img: "assets/xianggang.png",
      note: "随姑姑一家赴港游玩。",
    },
    {
      name: "横店",
      coord: [120.3, 29.19],
      date: "2012.07",
      tags: ["旅行"],
      province: "浙江省",
      city: "金华市",
      county: "东阳市",
      img: "assets/hengdian.png",
      note: "暑假前往影视城游览。",
    },
    {
      name: "长沙",
      coord: [112.938, 28.228],
      date: "2013.07",
      tags: ["旅行"],
      province: "湖南省",
      city: "长沙市",
      county: "",
      img: "assets/changsha.png",
      note: "暑假游张家界，顺路途经长沙。",
    },
    {
      name: "张家界",
      coord: [110.479, 29.117],
      date: "2013.07",
      tags: ["旅行", "户外"],
      province: "湖南省",
      city: "张家界市",
      county: "",
      img: "assets/zhangjiajie.png",
      note: "暑假游张家界。",
    },
    {
      name: "井冈山",
      coord: [114.165, 26.573],
      date: "2014.07",
      tags: ["旅行", "户外"],
      province: "江西省",
      city: "吉安市",
      county: "井冈山市",
      img: "assets/jinggangshan.png",
      note: "与父母一同红色之旅。",
    },
    {
      name: "北京",
      coord: [116.407, 39.904],
      date: "2014.08",
      tags: ["旅行"],
      province: "北京市",
      city: "",
      county: "",
      img: "assets/beijing.png",
      note: "随姑姑一家暑期出游。",
    },
    {
      name: "黄山",
      coord: [118.18, 30.13],
      date: "2015.07",
      tags: ["旅行", "户外"],
      province: "安徽省",
      city: "黄山市",
      county: "",
      img: "assets/huangshan.png",
      note: "与父母同游黄山。",
    },
    {
      name: "庐山西海",
      coord: [115.25, 29.13],
      date: "2015.09",
      tags: ["旅行", "放松"],
      province: "江西省",
      city: "九江市",
      county: "武宁县",
      img: "assets/lushanxihai.png",
      note: "泡温泉休闲游。",
    },
    {
      name: "西安",
      coord: [108.948, 34.263],
      date: "2016.07",
      tags: ["旅行"],
      province: "陕西省",
      city: "西安市",
      county: "",
      img: "assets/xian.png",
      note: "与妈妈、奶奶一同出游。",
    },
    {
      name: "明月山",
      coord: [114.3, 27.67],
      date: "2017.07",
      tags: ["旅行", "户外"],
      province: "江西省",
      city: "宜春市",
      county: "袁州区",
      img: "assets/mingyueshan.png",
      note: "与父母暑期登山。",
    },
    {
      name: "武汉",
      coord: [114.305, 30.593],
      date: "2021.06–08",
      tags: ["旅行"],
      province: "湖北省",
      city: "武汉市",
      county: "",
      img: "assets/wuhan.png",
      note: "高考结束后与高中同学结伴出游。",
    },
    {
      name: "宜昌",
      coord: [111.29, 30.692],
      date: "2021.06–08",
      tags: ["旅行", "户外"],
      province: "湖北省",
      city: "宜昌市",
      county: "",
      img: "assets/yichang.png",
      note: "高考结束后与高中同学结伴出游。",
    },
    {
      name: "神农架",
      coord: [110.429, 31.447],
      date: "2021.06–08",
      tags: ["旅行", "户外"],
      province: "湖北省",
      city: "神农架林区",
      county: "",
      img: "assets/shennongjia.png",
      note: "高考结束后与高中同学结伴出游。",
    },
    {
      name: "婺源",
      coord: [117.853, 29.278],
      date: "2022.07",
      tags: ["旅行", "摄影"],
      province: "江西省",
      city: "上饶市",
      county: "婺源县",
      img: "assets/wuyuan.png",
      note: "与同学前往素描写生。",
    },
    {
      name: "武功山",
      coord: [114.207, 27.448],
      date: "2023.02",
      tags: ["旅行", "户外"],
      province: "江西省",
      city: "萍乡市",
      county: "芦溪县",
      img: "assets/wugongshan.png",
      note: "与初中同学一同爬山，高山草甸云海绝美。",
    },
    {
      name: "庐山",
      coord: [116.0, 29.55],
      date: "2023.07",
      tags: ["旅行", "摄影"],
      province: "江西省",
      city: "九江市",
      county: "庐山市",
      img: "assets/lushan.png",
      note: "与同学前往水彩写生。",
    },
    {
      name: "合肥",
      coord: [117.28, 31.86],
      date: "2024.07 / 2025.01 / 2025.07",
      tags: ["旅行"],
      province: "安徽省",
      city: "合肥市",
      county: "",
      img: "assets/hefei.png",
      note: "三次参加快题集训。",
    },
    {
      name: "桐城",
      coord: [116.94, 31.05],
      date: "2017.07",
      tags: ["旅行"],
      province: "安徽省",
      city: "安庆市",
      county: "桐城市",
      img: "assets/tongcheng.png",
      note: "暑假与父母同游桐城。",
    },
    {
      name: "大觉山",
      coord: [116.98, 27.45],
      date: "2024.08",
      tags: ["旅行", "户外"],
      province: "江西省",
      city: "抚州市",
      county: "资溪县",
      img: "assets/dajueshan.png",
      note: "与初中同学前往漂流，夏日清凉刺激。",
    },
    {
      name: "靖安",
      coord: [115.36, 28.87],
      date: "2025.07",
      tags: ["旅行", "放松"],
      province: "江西省",
      city: "宜春市",
      county: "靖安县",
      img: "assets/jingan.png",
      note: "与姑姑一家度假休闲。",
    },
    {
      name: "钟祥",
      coord: [112.58, 31.169],
      date: "2025.07",
      tags: ["旅行"],
      province: "湖北省",
      city: "荆门市",
      county: "钟祥市",
      img: "assets/zhongxiang.png",
      note: "与女朋友一同旅游。",
    },
    {
      name: "信阳",
      coord: [114.091, 32.147],
      date: "2025.10",
      tags: ["旅行"],
      province: "河南省",
      city: "信阳市",
      county: "",
      img: "assets/xinyang.png",
      note: "与女朋友短途游玩。",
    },
    {
      name: "商洛",
      coord: [109.939, 33.868],
      date: "2025.12",
      tags: ["旅行"],
      province: "陕西省",
      city: "商洛市",
      county: "",
      img: "assets/shangluo.png",
      note: "赴商洛探望女朋友。",
    },
    {
      name: "苏州",
      coord: [120.619, 31.299],
      date: "2025.12",
      tags: ["旅行"],
      province: "江苏省",
      city: "苏州市",
      county: "",
      img: "assets/suzhou.png",
      note: "参加研究生入学考试初试。",
    },
    {
      name: "武当山",
      coord: [111.004, 32.4],
      date: "2026.04",
      tags: ["旅行", "户外"],
      province: "湖北省",
      city: "十堰市",
      county: "丹江口市",
      img: "assets/wudangshan.png",
      note: "与女朋友同游。",
    },
    {
      name: "青岛",
      coord: [120.382, 36.067],
      date: "2026.06",
      tags: ["旅行"],
      province: "山东省",
      city: "青岛市",
      county: "",
      img: "assets/qingdao.png",
      note: "拜访未来导师韩青教授并汇报工作。",
    },
    {
      name: "麻城",
      coord: [115.022, 31.18],
      date: "2026.06",
      tags: ["旅行"],
      province: "湖北省",
      city: "黄冈市",
      county: "麻城市",
      img: "assets/macheng.png",
      note: "与女朋友一同旅游。",
    },
  ],

  /* ---------- 5. 钓鱼种类记录（鱼种图鉴，按生物学分类）----------
   * 替换原“垂钓记录”板块。每条为钓到过的一种鱼：
   *   emoji   形象图标（emoji 即可）
   *   name    鱼名
   *   order   生物分类「目」（用于分组大标题，如 鲤形目）
   *   family  生物分类「科」（用于分组小标题，如 鲤科）
   *   desc    简介 / 习性
   *   tags    标签（用于顶部标签云联动筛选；建议沿用既有标签，如 垂钓/户外/淡水/路亚）
   *   record  战绩 / 最大尺寸（可选，如 "最大 12 斤"）
   *   story   最难忘的一竿（可选，支持 Markdown）
   *   img     鱼获照片地址（可选；留空则显示 emoji）
   * 想增删鱼种或填真实数据，直接改下面这个数组即可；分组由 order / family 自动生成。
   */
  fishSpecies: [
    // ===== 鲤形目 Cypriniformes · 鲤科 Cyprinidae =====
    {
      emoji: "🐟",
      name: "鲫鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型底层杂食鱼，肉嫩味鲜，台钓入门首选目标。",
      tags: ["垂钓", "淡水"],
      record: "野生常见 3–8 两",
      story: "野塘连杆，台钓开竿第一口常是它。",
      img: "assets/jiyu.jpg",
    },
    {
      emoji: "🐠",
      name: "鲤鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "底层杂食大鱼，力沉、溜鱼过瘾，俗称“鲤拐子”。",
      tags: ["垂钓", "淡水"],
      record: "2斤",
      story: "水库守钓最稳的目标，一尾大鲤能遛到手酸。",
      img: "assets/liyu.jpg",
    },
    {
      emoji: "🐟",
      name: "白条",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型上层鱼，抢食活跃，常闹窝但也能连杆解闷。",
      tags: ["垂钓", "淡水"],
      record: "20cm+",
      story: "鱼口轻时白条不断，解闷神器。",
      img: "assets/baitiao.png",
    },
    {
      emoji: "🐟",
      name: "蒙古红鲌",
      order: "鲤形目",
      family: "鲤科",
      desc: "中上层掠食鱼，凶猛、游速快，红鳍明显。",
      tags: ["垂钓", "淡水"],
      record: "",
      story: "路亚亮片常炸水追饵，手感刺激。",
      img: "assets/mengguhongbo.png",
    },
    {
      emoji: "🐟",
      name: "翘嘴鲌",
      order: "鲤形目",
      family: "鲤科",
      desc: "中上层掠食鱼，嘴上翘、凶猛，路亚与浮钓都爱咬。",
      tags: ["垂钓", "淡水"],
      record: "最大 3 斤+",
      story: "清晨连竿翘嘴，水面炸水那一刻最上头。",
      img: "assets/qiaozuiboba.png",
    },
    {
      emoji: "🐟",
      name: "赤眼鳟",
      order: "鲤形目",
      family: "鲤科",
      desc: "中下层杂食鱼，眼上半部红色，俗称“红眼”。",
      tags: ["垂钓", "淡水"],
      record: "30cm+",
      story: "溪流缓水区常见，吃口干净利落。",
      img: "assets/chiyanzun.png",
    },
    {
      emoji: "🐟",
      name: "鳡鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "大型掠食鱼，泳速极快，有“水中老虎”之称。",
      tags: ["垂钓", "淡水"],
      record: "30cm+",
      story: "大水面守钓偶遇，中钩后狂奔，一辈子想再遇一回。",
      img: "assets/ganyu.jpg",
    },
    {
      emoji: "🐟",
      name: "条纹小鲃",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型鲤科鱼，体侧纵纹明显，多栖息南方溪流。",
      tags: ["垂钓", "淡水"],
      record: "6–8cm",
      story: "溪流浅滩群游，细线小钩最对味。",
      img: "assets/tiaowenxiaoba.png",
    },
    {
      emoji: "🐟",
      name: "草鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "大型草食性鱼，冲劲足、遛鱼带感。",
      tags: ["垂钓", "淡水"],
      record: "最大 5斤",
      story: "守钓一天一尾大草鱼，溜到疑心自己胳膊废了。",
      img: "assets/caoyu.jpg",
    },
    {
      emoji: "🐟",
      name: "马口鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型溪流掠食鱼，雄鱼婚姻色艳，爱抢亮片。",
      tags: ["垂钓", "淡水"],
      record: "6两",
      story: "溪流路亚连杆，阳光下鳞片闪光很漂亮。",
      img: "assets/makouyu.jpg",
    },
    {
      emoji: "🐟",
      name: "麦穗鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型底层鱼，常闹窝，生命力极强。",
      tags: ["垂钓", "淡水"],
      record: "常见 10–15cm",
      story: "闹窝专业户，钓大鱼的“前菜”。",
      img: "assets/maisuiyu.jpg",
    },
    {
      emoji: "🐟",
      name: "鳑鲏",
      order: "鲤形目",
      family: "鲤科",
      desc: "小型鱼，繁殖需依托河蚌，雄鱼色彩艳丽。",
      tags: ["垂钓", "淡水"],
      record: "6–8cm",
      story: "清澈浅水常见，颜色好看，适合生态观察。",
      img: "assets/pangpi.png",
    },
    {
      emoji: "🐟",
      name: "鳊鱼",
      order: "鲤形目",
      family: "鲤科",
      desc: "中上层群居鱼，吃口轻快，常成群进窝。",
      tags: ["垂钓", "淡水"],
      record: "15cm",
      story: "与鲫鱼同获，群口时一个窝连拉。",
      img: "assets/bianyu.png",
    },
    // ===== 鲤形目 Cypriniformes · 鳅科 Cobitidae =====
    {
      emoji: "🐟",
      name: "泥鳅",
      order: "鲤形目",
      family: "鳅科",
      desc: "小型底栖鳅类，体表黏滑，钻泥能力强。",
      tags: ["垂钓", "淡水"],
      record: "10cm",
      story: "水田沟渠随手就能摸到，滑不溜手。",
      img: "assets/niqiu.jpg",
    },
    // ===== 鲇形目 Siluriformes · 鲇科 Siluridae =====
    {
      emoji: "🐟",
      name: "鲇鱼",
      order: "鲇形目",
      family: "鲇科",
      desc: "底层无鳞掠食鱼，夜行性，口须明显。",
      tags: ["垂钓", "淡水"],
      record: "20cm",
      story: "夏夜守钓，一口闷竿最带劲。",
      img: "assets/nianyu.png",
    },
    // ===== 鲇形目 Siluriformes · 鲿科 Bagridae =====
    {
      emoji: "🐟",
      name: "黄颡鱼",
      order: "鲇形目",
      family: "鲿科",
      desc: "小型鲿类，黄绿色，胸鳍硬刺有毒，俗称“昂刺”。",
      tags: ["垂钓", "淡水"],
      record: "20cm",
      story: "被硬刺扎过手，麻半天，但肉嫩鲜甜。",
      img: "assets/huangsangyu.png",
    },
    // ===== 合鳃目 Synbranchiformes · 合鳃科 Synbranchidae =====
    {
      emoji: "🐍",
      name: "黄鳝",
      order: "合鳃目",
      family: "合鳃科",
      desc: "鳗形穴居鱼，无鳞、黏液多，夜行捕食。",
      tags: ["垂钓", "淡水"],
      record: "60cm+",
      story: "田埂鳝洞一钩一尾，手感滑溜又带劲。",
      img: "assets/huangshanyu.jpg",
    },
    // ===== 合鳃目 Synbranchiformes · 刺鳅科 Mastacembelidae =====
    {
      emoji: "🪱",
      name: "刺鳅",
      order: "合鳃目",
      family: "刺鳅科",
      desc: "鳗形带背刺，底栖，俗称“刀鳅”。",
      tags: ["垂钓", "淡水"],
      record: "15cm",
      story: "溪石缝里才见着，背刺扎手要小心。",
      img: "assets/ciqiu.jpg",
    },
    // ===== 鲈形目 Perciformes · 鳢科 Channidae =====
    {
      emoji: "🐟",
      name: "黑鱼",
      order: "鲈形目",
      family: "鳢科",
      desc: "凶猛掠食鱼，护幼性强，肉质紧实。",
      tags: ["垂钓", "淡水"],
      record: "2斤+",
      story: "雷强打黑一口吞饵，炸水最猛。",
      img: "assets/heiyu.jpg",
    },
    // ===== 鲈形目 Perciformes · 虾虎鱼科 Gobiidae =====
    {
      emoji: "🐟",
      name: "虾虎鱼",
      order: "鲈形目",
      family: "虾虎鱼科",
      desc: "底层小型鱼，胸鳍愈合如吸盘，常栖砂砾底。",
      tags: ["垂钓", "淡水"],
      record: "10cm",
      story: "浅滩砂底常见，趴在石头上一动不动。",
      img: "assets/xiaohuyu.jpg",
    },
    // ===== 鲈形目 Perciformes · 太阳鱼科 Centrarchidae =====
    {
      emoji: "🐟",
      name: "淡水鲈鱼",
      order: "鲈形目",
      family: "太阳鱼科",
      desc: "即大口黑鲈（俗称加州鲈），引进的淡水掠食鱼，口大、肉食性，游速快、搏鱼有力。",
      tags: ["垂钓", "淡水"],
      record: "20cm",
      story: "路亚亮片常炸水咬饵，中钩后暴冲，手感比想象中猛。",
      img: "assets/danshuiluyu.jpg",
    },
  ],

  /* ---------- 6. Markdown 随笔 / 日志 ----------
   * 整段支持 Markdown，可写多篇（每篇含 title 与 content）。
   */
  journal: [
    {
      title: "关于这个网站",
      date: "2026-07-15",
      content: [
        "这个站点完全用 **静态网页** 搭成，地图用的是 ECharts + 阿里 DataV 的中国地理数据。",
        "",
        "## 为什么自己做",
        "- 现成的博客平台太重，我想把 *旅行* 和 *垂钓* 放在同一张地图上；",
        "- 顺手练了练前端；",
        "- 数据都在 `js/data.js` 里，想改随时改。",
        "",
        "> 如果你也想要同款，把 `data.js` 换成你自己的故事即可。",
      ].join("\n"),
    },
  ],
};

/* 常见城市坐标速查（需要时复制到上面的 coord）：
   北京 [116.407,39.904]  上海 [121.473,31.23]  广州 [113.264,23.129]
   深圳 [114.057,22.543]  成都 [104.066,30.572]  杭州 [120.155,30.274]
   西安 [108.948,34.263]  重庆 [106.551,29.563]  武汉 [114.305,30.593]
   南京 [118.797,32.06]   昆明 [102.833,24.88]   拉萨 [91.14,29.645]
   哈尔滨 [126.642,45.756] 三亚 [109.511,18.252] 乌鲁木齐 [87.617,43.792]
*/
